# version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gravitylens
      POSTGRES_PASSWORD: gravitylens123
      POSTGRES_DB: gravitylens_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://gravitylens:gravitylens123@db:5432/gravitylens_db
    depends_on:
      - db
    volumes:
      - ./backend:/app
    env_file:
    - .env

volumes:
  postgres_data: